---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - recipe[nginx]
      - recipe[trion-cookbooks::disable_sites]
      - recipe[trion-cookbooks::git_install]
      - recipe[trion-cookbooks::setup_www_root]
      - recipe[trion-cookbooks::deploy_japhet_in]
      - recipe[trion-cookbooks::deploy_tributetothebeast_com]
    attributes:
