---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: debian/jessie64
  # - name: debian-8.2.0
  # - name: debian-8.3.0

suites:
  - name: default
    run_list:
      - recipe[hostname]
      - recipe[trion::install_httpd]
      # - recipe[trion::disable_sites]
      # - recipe[trion::setup_www_root]
      # - recipe[git]
      # - recipe[trion::deploy_default_site]
      # - recipe[trion::deploy_japhet_in]
      # - recipe[trion::deploy_tributetothebeast_com]
      # - recipe[trion::deploy_prorthymix_com]
      # - recipe[build-essential]
      # - recipe[trion::install_octopress]
      # - recipe[nodejs]
      # - recipe[trion::deploy_blog_karun_me]
      # - recipe[trion::deploy_karunab_com]
      # - recipe[trion::deploy_karun_me]
      # - recipe[trion::deploy_karun_japhet_in]
      # These changes need to be duplicated in roles/webserver.rb for
      # production deployments using chef solo
    attributes:

name: "Cybershark"
