---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: debian/jessie64
  # - name: debian-8.2.0
  # - name: debian-8.3.0

suites:
  - name: default
    run_list:
      - recipe[trion::shim_includer]
    attributes:

name: "Cybershark"
