---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian/jessie64
  - name: ubuntu/vivid64

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    attributes:
