---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - recipe[bumblebee-cookbooks::default]
    attributes:
